---
- name: install gem
  shell: gem install passenger -v {{ passenger_version }}
  notify: rbenv rehash

- name: check if already compiled
  shell: passenger-install-apache2-module --snippet | cut -d " " -f 3 | head -n 1 | xargs test -f
  register: passenger_compiled
  ignore_errors: true

- name: compile module
  shell: passenger-install-apache2-module --auto
  when: passenger_compiled|failed

